package ninja.bryansills.loudping.app.theme

import androidx.annotation.ColorInt
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb

val primaryLightMediumContrast = Color(0xFF6A340F)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFFA7643C)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF673052)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF9F6185)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF514100)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF887324)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F6)
val onBackgroundLightMediumContrast = Color(0xFF221A15)
val surfaceLightMediumContrast = Color(0xFFFFF8F6)
val onSurfaceLightMediumContrast = Color(0xFF221A15)
val surfaceVariantLightMediumContrast = Color(0xFFF4DED4)
val onSurfaceVariantLightMediumContrast = Color(0xFF4E4039)
val outlineLightMediumContrast = Color(0xFF6C5C54)
val outlineVariantLightMediumContrast = Color(0xFF88776F)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF382E29)
val inverseOnSurfaceLightMediumContrast = Color(0xFFFFEDE5)
val inversePrimaryLightMediumContrast = Color(0xFFFFB68D)
val surfaceDimLightMediumContrast = Color(0xFFE8D7CF)
val surfaceBrightLightMediumContrast = Color(0xFFFFF8F6)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFFF1EB)
val surfaceContainerLightMediumContrast = Color(0xFFFCEAE3)
val surfaceContainerHighLightMediumContrast = Color(0xFFF6E5DD)
val surfaceContainerHighestLightMediumContrast = Color(0xFFF0DFD7)

val primaryDarkMediumContrast = Color(0xFFFFBC97)
val onPrimaryDarkMediumContrast = Color(0xFF2A0E00)
val primaryContainerDarkMediumContrast = Color(0xFFC87F55)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFFFB5DD)
val onSecondaryDarkMediumContrast = Color(0xFF310223)
val secondaryContainerDarkMediumContrast = Color(0xFFBF7CA2)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFE3C971)
val onTertiaryDarkMediumContrast = Color(0xFF1C1600)
val tertiaryContainerDarkMediumContrast = Color(0xFFA68F3E)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF1A120D)
val onBackgroundDarkMediumContrast = Color(0xFFF0DFD7)
val surfaceDarkMediumContrast = Color(0xFF1A120D)
val onSurfaceDarkMediumContrast = Color(0xFFFFFAF8)
val surfaceVariantDarkMediumContrast = Color(0xFF52443C)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDBC7BD)
val outlineDarkMediumContrast = Color(0xFFB29F96)
val outlineVariantDarkMediumContrast = Color(0xFF918077)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFF0DFD7)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF322823)
val inversePrimaryDarkMediumContrast = Color(0xFF713914)
val surfaceDimDarkMediumContrast = Color(0xFF1A120D)
val surfaceBrightDarkMediumContrast = Color(0xFF413732)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF140D08)
val surfaceContainerLowDarkMediumContrast = Color(0xFF221A15)
val surfaceContainerDarkMediumContrast = Color(0xFF271E19)
val surfaceContainerHighDarkMediumContrast = Color(0xFF312823)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3D332E)

@ColorInt val primaryAsColorInt: Int = primaryLightMediumContrast.toArgb()

@ColorInt val primaryDarkAsColorInt: Int = primaryDarkMediumContrast.toArgb()
