#!/bin/sh
set -euo pipefail

# Runs Ktfmt on all staged files. If there are new changes, you got to add them to the commit.
exit_code=0
OUTPUT="$(./scripts/ktfmt.sh --staged --plain --set-exit-if-changed &>/dev/null)" || exit_code=$?

if [ "$exit_code" -ne 0 ]; then
  echo "There were formatting changes to some of your staged changes. Please stage them now."
  exit 1
fi
