name: Deploy static content to Pages

on:
  workflow_dispatch:
  schedule:
    # 5:33 AM EST / 6:33 AM EDT
    - cron: "33 10 * * *"

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Push out the latest HTML files

    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v6
        with:
          ref: 'ghpages'
          fetch-depth: 0

      - name: Prepare development environment
        uses: ./.github/actions/prepare-environment

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Merge latest from 'main' git branch
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

          git merge origin/main

          git push origin ghpages

      - name: Generate HTML for the static site
        run: ./gradlew :html:builder:run

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'html/builder/build/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
